### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by LinBoyan** [IceKyrin/lrc_download#2]
Traceback (most recent call last):
  File "main.py", line 178, in <module>
  File "main.py", line 62, in get_file_info
  File "main.py", line 31, in get_info_dict
  File "get_info.py", line 14, in auto
  File "get_info.py", line 23, in mp3
  File "mutagen\_file.py", line 49, in __init__
  File "mutagen\_util.py", line 140, in wrapper
  File "mutagen\id3\_file.py", line 406, in load
  File "mutagen\_util.py", line 169, in wrapper
  File "mutagen\mp3\__init__.py", line 403, in __init__
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
[5912] Failed to execute script 'main' due to unhandled exception!

**Comment by IceKyrin** [comment]
can't sync to MPEG frame：无法同步mpeg帧
只支持mp3和flac，MP4格式不支持
如果是MP3的话，可能是文件损坏或者那个歌曲文件没有包含歌曲tag信息
建议文件夹下只保留mp3和flac格式
